//
//  MainNavigationPresenter.m
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "MainNavigationPresenter.h"
#import "MainNavigationProtocols.h"

@interface MainNavigationPresenter () <MainNavigationPresenterInterface>
@property (strong, nonatomic) NSObject<MainNavigationWireframeInterface>* router;
@end

@implementation MainNavigationPresenter

- (instancetype)initWithView:(NSObject<MainNavigationView>*)view router:(NSObject<MainNavigationWireframeInterface>*)router {
    self = [super init];
    if (self) {
        self.view = view;
        self.router = router;
    }
    return self;
}

- (void)viewDidAppear {
    //Default implementation
}

- (void)viewDidDissappear {
    //Default implementation
}

- (void)viewDidLoad {
    //Default implementation
}

- (void)viewWillAppear {
    //Default implementation
}

- (void)viewWillDissappear {
    //Default implementation
}

@end
