//
//  MainNavigationPresenter.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "MainNavigationProtocols.h"

@interface MainNavigationPresenter: NSObject<MainNavigationPresenterInterface>
@property (nonatomic, weak) NSObject<MainNavigationView> *view;
- (instancetype)initWithView:(NSObject<MainNavigationView>*)view
                      router:(NSObject<MainNavigationWireframeInterface>*)router;
@end


