//
//  PhotoFinderRouter.m
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "PhotoFinderRouter.h"
#import "PhotoFinderProtocols.h"
#import "PhotoEditorViewController.h"
#import "MainNavigationTabBarController.h"

@implementation PhotoFinderRouter

- (void)navigateToDismiss { 
    [self.viewController dismissViewControllerAnimated:true completion:nil];
}

- (void)navigateTo:(UIViewController *)vc {
    if([vc isKindOfClass:[UINavigationController class]]){
        [self.viewController presentViewController:vc animated:true completion:nil];
    } else if ([vc isKindOfClass:[UIViewController class]]) {
        if (self.viewController.navigationController){
            [self.viewController.navigationController pushViewController:vc animated:true];
        } else {
            [self.viewController presentViewController:vc animated:true completion:nil];
        }
    }
}

- (void)navigateToPhotoEditorWithImage:(UIImage *)image
{
    MainNavigationTabBarController *rootTabbar = (MainNavigationTabBarController *)[UIApplication sharedApplication].delegate.window.rootViewController;
    rootTabbar.photoEditor.image = image;
    rootTabbar.selectedIndex = 1;
}

@end
