//
//  PhotoEditorRouter.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "PhotoEditorProtocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface PhotoEditorRouter : NSObject<PhotoEditorWireframeInterface>

@property (weak, nonatomic) UIViewController *viewController;

@end

NS_ASSUME_NONNULL_END