//
//  PhotoEditorViewController.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>
#import "PhotoEditorProtocols.h"

NS_ASSUME_NONNULL_BEGIN

@interface PhotoEditorViewController : UIViewController<PhotoEditorView>

@property (nonatomic, strong) NSObject<PhotoEditorPresenterInterface>* presenter;
@property (nonatomic, strong) UIImage *image;

- (instancetype)initWithImage:(UIImage *)image;

@end

NS_ASSUME_NONNULL_END
