//
//  PhotoEditorAssembly.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <UIKit/UIKit.h>

@interface PhotoEditorAssembly: NSObject

+ (UIViewController *)createModuleWithImage:(UIImage *)image;

@end
