//
//  PhotoEditorPresenter.m
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "PhotoEditorPresenter.h"
#import "PhotoEditorProtocols.h"

@interface PhotoEditorPresenter () <PhotoEditorPresenterInterface>
@property (strong, nonatomic) NSObject<PhotoEditorWireframeInterface>* router;
@end

@implementation PhotoEditorPresenter

- (instancetype)initWithView:(NSObject<PhotoEditorView>*)view router:(NSObject<PhotoEditorWireframeInterface>*)router {
    self = [super init];
    if (self) {
        self.view = view;
        self.router = router;
    }
    return self;
}

- (void)viewDidAppear {
    //Default implementation
}

- (void)viewDidDissappear {
    //Default implementation
}

- (void)viewDidLoad {
    //Default implementation
}

- (void)viewWillAppear {
    //Default implementation
}

- (void)viewWillDissappear {
    //Default implementation
}

@end
