//
//  PhotoEditorPresenter.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "PhotoEditorProtocols.h"

@interface PhotoEditorPresenter: NSObject<PhotoEditorPresenterInterface>
@property (nonatomic, weak) NSObject<PhotoEditorView> *view;
- (instancetype)initWithView:(NSObject<PhotoEditorView>*)view
                      router:(NSObject<PhotoEditorWireframeInterface>*)router;
@end


