//
//  PhotoFinderPresenter.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import "PhotoFinderProtocols.h"

@interface PhotoFinderPresenter: NSObject<PhotoFinderPresenterInterface>
@property (nonatomic, weak) NSObject<PhotoFinderView> *view;
- (instancetype)initWithView:(NSObject<PhotoFinderView>*)view
                      router:(NSObject<PhotoFinderWireframeInterface>*)router
                 searchQuery:(NSString *)query;
@end


