//
//  MainNavigationAssembly.m
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "MainNavigationAssembly.h"
#import "MainNavigationTabBarController.h"
#import "MainNavigationPresenter.h"
#import "MainNavigationProtocols.h"
#import "MainNavigationRouter.h"

@interface MainNavigationAssembly ()

@end

@implementation MainNavigationAssembly

+ (UIViewController *)createModule {
    MainNavigationTabBarController *view = [[MainNavigationTabBarController alloc] init];
    MainNavigationRouter *router = [[MainNavigationRouter alloc] init];
    MainNavigationPresenter *presenter = [[MainNavigationPresenter alloc] initWithView:view router:router];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
