//
//  PhotoFinderAssembly.m
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "PhotoFinderAssembly.h"
#import "PhotoFinderViewController.h"
#import "PhotoFinderPresenter.h"
#import "PhotoFinderProtocols.h"
#import "PhotoFinderRouter.h"

@interface PhotoFinderAssembly ()

@end

@implementation PhotoFinderAssembly

+ (UIViewController *)createModuleWithSearchQuery:(NSString *)query {
    PhotoFinderViewController *view = [[PhotoFinderViewController alloc] init];
    PhotoFinderRouter *router = [[PhotoFinderRouter alloc] init];
    PhotoFinderPresenter *presenter = [[PhotoFinderPresenter alloc] initWithView:view router:router searchQuery:query];
    view.presenter = presenter;
    router.viewController = view;
    return view;
}

@end
