//
//  PhotoFinderProtocols.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>
#import "Photo.h"


NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol PhotoFinderWireframeInterface <NSObject>

//example
@required
- (void)navigateToDismiss;
- (void)navigateToPhotoEditorWithImage:(UIImage *)image;

@end

@protocol PhotoFinderView <NSObject>

- (void)displayPhotos:(NSArray <Photo *>*)photos;
- (void)displaySeachQuery:(NSString *)query;

@end

@protocol PhotoFinderPresenterInterface <NSObject>

- (void)didSelectImageCellAtIP:(NSIndexPath *)ip;
- (void)didEnterSearchFieldWithQuery:(NSString *)query;

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

@end


NS_ASSUME_NONNULL_END
