//
//  PhotoEditorProtocols.h
//  NSUrlRequestProject
//
//  Created pockerhead on 18/04/2019.
//  Copyright © 2019 Alexey Levanov. All rights reserved.
//
//  Template generated by Balashov Artem @pockerhead
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

//Router implement navigateTo func
@protocol PhotoEditorWireframeInterface <NSObject>

//example
@required - (void)navigateToDismiss;

@end

@protocol PhotoEditorView <NSObject>

@end

@protocol PhotoEditorPresenterInterface <NSObject>

- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewDidAppear;
- (void)viewWillDissappear;
- (void)viewDidDissappear;

@end


NS_ASSUME_NONNULL_END
